In [1]:
from array import array 
from random import random
floats = array('d', (random() for i in range(10**7))) 
floats[-1]





0.17416555256084998

In [2]:
fp = open('floats.bin', 'wb')
floats.tofile(fp) 
fp.close()
floats2 = array('d') 
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) 
fp.close()
floats2[-1] 

0.17416555256084998

In [12]:
a = array('d',(5,8,3,9,2,1,7))
a = array(a.typecode, sorted(a,reverse=True))
a

array('d', [9.0, 8.0, 7.0, 5.0, 3.0, 2.0, 1.0])

In [13]:

octets = array('B', range(6)) 
m1 = memoryview(octets)
m1.tolist()



[0, 1, 2, 3, 4, 5]

In [14]:
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [15]:
m3 = m1.cast('B', [3, 2]) 
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [ ]:
m2[1,1]=22
m3[1,1]=33
octets # структуры. созданные через memoryview, имеют общую память и изменяются каскадно

array('B', [0, 1, 2, 33, 22, 5])

In [ ]:
from pympler import asizeof # массив NumPy позволяет сильно экономить память
import numpy as np
a=list(range(100000))
b=np.arange(100000)
c=np.arange(100000,dtype=np.int32)
print(asizeof.asizeof(a))
print(asizeof.asizeof(b))
print(asizeof.asizeof(c))

4000056
800128
400128


In [15]:
d=np.arange(12)
d.shape # Иноформация об размерности массива
d.shape=4,3
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
d[1]

array([3, 4, 5])

In [17]:
d[:,1]

array([ 1,  4,  7, 10])

In [18]:
d[2,1]

np.int64(7)

In [19]:
d.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [20]:
np.save('floats-10M', d)
floats2 = np.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([[18, 24, 30],
        [36, 42, 48],
        [54, 60, 66]])