In [1]:
import numpy as np
import pandas as pd

In [3]:
lst=np.arange(0,10,1)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Создание массива любой размерности, любым значением и типом данных

arr3=np.full((3,3), True, dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Фильтрация np.array через маску

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
# Замена значений через маску или np.where

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.where(arr%2!=0,-1,arr)

# Или
# arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
arr = np.arange(10)
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# вертикальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=0)

# Или
# np.vstack((a, b))

# Или 
# np.r_[a, b]
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# горизонтальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=1)
res

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# Генерация повторяющейся последовательности элементов по разным паттернам

a = np.array([1,2,3])

res=np.repeat(a, 3)
print(res)

res2=np.tile(a,3)
print(res2)

result=np.r_[np.repeat(a, 3), np.tile(a,3)]
result

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [3]:
# Поиск общих уникальных элементов в двух массивах

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.intersect1d(a,b)
res

array([2, 4])

In [10]:
# Фильтрация массива по наличию общих элементов с другим массивом

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])


res=np.setdiff1d(a,b)
res

array([1, 2, 3, 4])

In [27]:
# Поиск позиций, где элементы совпадают

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.where(a==b)
res

(array([1, 3, 5, 7]),)

In [32]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

# Метод 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Метод 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

array([ 6,  9, 10])

In [40]:
# Пример квази-векторизации через np.vecrotize


# Лучше использовать встроенную векторизованную функцию, она в сотни раз быстрее
# res = np.maximum(a, b)

def maxx(x, y):
    "Получите максимум два предмета"
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

res = np.vectorize(maxx, otypes=[float])(a,b)

res

array([6., 7., 9., 8., 9., 7., 5.])