In [1]:
import numpy as np
import pandas as pd

In [3]:
lst=np.arange(0,10,1)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Создание массива любой размерности, любым значением и типом данных

arr3=np.full((3,3), True, dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Фильтрация np.array через маску

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
# Замена значений через маску или np.where

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.where(arr%2!=0,-1,arr)

# Или
# arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
arr = np.arange(10)
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# вертикальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=0)

# Или
# np.vstack((a, b))

# Или 
# np.r_[a, b]
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# горизонтальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=1)
res

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# Генерация повторяющейся последовательности элементов по разным паттернам

a = np.array([1,2,3])

res=np.repeat(a, 3)
print(res)

res2=np.tile(a,3)
print(res2)

result=np.r_[np.repeat(a, 3), np.tile(a,3)]
result

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [3]:
# Поиск общих уникальных элементов в двух массивах

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.intersect1d(a,b)
res

array([2, 4])

In [10]:
# Фильтрация массива по наличию общих элементов с другим массивом

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])


res=np.setdiff1d(a,b)
res

array([1, 2, 3, 4])

In [27]:
# Поиск позиций, где элементы совпадают

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.where(a==b)
res

(array([1, 3, 5, 7]),)

In [32]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

# Метод 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Метод 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

array([ 6,  9, 10])

In [40]:
# Пример квази-векторизации через np.vecrotize


# Лучше использовать встроенную векторизованную функцию, она в сотни раз быстрее
# res = np.maximum(a, b)

def maxx(x, y):
    "Получите максимум два предмета"
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

res = np.vectorize(maxx, otypes=[float])(a,b)

res

array([6., 7., 9., 8., 9., 7., 5.])

In [5]:
# Изменение порядка элементов во вложенных массивах (столбцах)

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[:, [1,0,2]]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [9]:
# Изменение порядка элементов во вложенных массивах (строках)

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[[1,0,2], :]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [15]:
# Сортировка в обратном порядке строк

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[::-1]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [37]:
# Обратная сортировка столбцов в многомерном массиве

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[:,::-1]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [63]:
# Генерация массива float от 5 до 10 с заданным shape через новый API np.random

rng = np.random.default_rng(seed=42)
arr = rng.uniform(5, 10, (5, 3))
arr

array([[8.86978024, 7.1943922 , 9.2929896 ],
       [8.48684015, 5.47088674, 9.87811176],
       [8.80569851, 8.93032153, 5.64056816],
       [7.25192969, 6.85399012, 9.63382494],
       [8.2193256 , 9.11380807, 7.21707099]])

In [66]:
# Ограничение до 3 знаков после запятой
# Аналог pd.get/set_options в pandas

rand_arr = np.random.random((5,3))


np.set_printoptions(precision=3)

rand_arr

array([[0.924, 0.526, 0.92 ],
       [0.956, 0.025, 0.71 ],
       [0.242, 0.694, 0.21 ],
       [0.253, 0.242, 0.894],
       [0.017, 0.847, 0.84 ]])

In [68]:
np.set_printoptions(precision=6, suppress=True)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [69]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [71]:
import sys

np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [72]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Вывести первые 3 строки
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [8]:
# Извлечение определенного столбца из одномерного структурированного массива


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d[:3])

species = np.array([row[4] for row in iris_1d])
print(species[:5])


[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa')]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [41]:
# Преобразование одномерного структурированного массива в двумерный числовой массив с исключением элементов

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d[:3])

# Метод 1: Преобразуйте каждую строку в список и получите первые 4 элемента.
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4])

# Альтернативный метод 2: Импортировать только первые 4 столбца из исходного URL-адреса
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# print(iris_2d[:4])

# Метод 3: Извлекаем все числовые столбцы (0-3)
# iris_2d = iris_1d[:, :4]

[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa')]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [42]:
# Используем usecols, чтобы вытащить элементы из вложенных массивов и преобразовать в отдельный "столбец"

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Или извлекаем первый столбец (sepallength)
# sepallength = iris[:, 0]  # все строки, 0-й столбец

print(iris[:3])
print(sepallength)
print(type(sepallength))

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
<class 'numpy.ndarray'>
5.843333333333334 5.8 0.8253012917851409


In [46]:
# Мин-макс нормализация — это стандартный этап предварительной обработки для алгоритмов машинного обучения 
# (например, KNN, SVM), чувствительных к масштабу признаков.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength[:5])

s_max, s_min = sepallength.max(), sepallength.min()
s = (sepallength - s_min) / (s_max - s_min)
print(s)

[5.1 4.9 4.7 4.6 5. ]
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.361111

In [51]:

# функция Softmax преобразует исходные оценки в вероятности и является конечной функцией активации в большинстве классификационных нейронных сетей.
# np.exp — векторизованная функция, применяется к каждому элементу массива

# Что здесь делает exp:
# Превращает любые числа (отрицательные, нули, положительные) в положительные
# Усиливает разницу между значениями (большие числа становятся ещё больше)
# После деления на сумму получаем вероятности


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    """Численно стабильный softmax."""
    # Вычитаем максимум — это не меняет результат, но предотвращает overflow
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

result = softmax(sepallength)
print("Softmax для sepallength:")
print(result)
print(f"\nСумма: {result.sum():.10f}")  # 1.0000000000
print(f"Мин: {result.min():.6f}")
print(f"Макс: {result.max():.6f}")

Softmax для sepallength:
[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

res=np.percentile(sepallength,q=[5,95])
res

array([4.6  , 7.255])

In [8]:
# Вставьте данные np.nan в 20 случайных позиций в iris_2d


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Локальный генератор
rng = np.random.default_rng(seed=100)

# ✅ ГЕНЕРИРУЕМ случайные индексы
n_rows = iris_2d.shape[0]  # 150 (размер)
n_cols = 4                  # 4 (размер)

# Генерируем 20 случайных номеров строк (от 0 до 149)
rows = rng.integers(0, n_rows, size=20)

# Генерируем 20 случайных номеров столбцов (от 0 до 3)
cols = rng.integers(0, n_cols, size=20)

# Заменяем на NaN
iris_2d[rows, cols] = np.nan

print(iris_2d[:10])

[[nan b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' nan b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [23]:
# Нахождение позиций с np.nan и количество этих позиций

sepallength=iris_2d[:,0]

# Проверяем каждый элемент, если np.isnan вызывает TypeError
nan_mask = np.array([isinstance(x, float) and np.isnan(x) for x in sepallength])


print(f'Количество np.nan в массиве: {len(sepallength[nan_mask])}')

indices=np.where(nan_mask)
print(f'Позиции где np.nan: {indices}')

Количество np.nan в массиве: 4
Позиции где np.nan: (array([  0,  66, 107, 138]),)


In [25]:
# Фильтрация многомерного массива по нескольким условиям

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

sepallength=iris_2d[:,0]
petallength=iris_2d[:,2]

res=iris_2d[(sepallength<5.0) & (petallength>1.5)]
res

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [42]:
# Фильтрация строк хотя бы с одним пропущенным значением

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Локальный генератор
rng = np.random.default_rng(seed=100)

# ✅ ГЕНЕРИРУЕМ случайные индексы
n_rows = iris_2d.shape[0]  # 150 (размер)
n_cols = 4                  # 4 (размер)

# Генерируем 20 случайных номеров строк (от 0 до 149)
rows = rng.integers(0, n_rows, size=20)

# Генерируем 20 случайных номеров столбцов (от 0 до 3)
cols = rng.integers(0, n_cols, size=20)

# Заменяем на NaN
iris_2d[rows, cols] = np.nan

print(iris_2d[:10])


nan_rows=np.array([any(np.isnan(row)) for row in iris_2d])

iris_2d[~nan_rows][:10]

[[nan 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 nan 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2]])

In [6]:
from scipy.stats import pearsonr

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

sepallength=iris_2d[:,0]
petallength=iris_2d[:,2]

pearson=np.corrcoef(sepallength, petallength)[0,1]
print(f'Через numpy: {pearson}')

r, p_value = pearsonr(sepallength, petallength)
print(f'Через scipy:\nКорреляция: {r}\nP_value: {p_value}')



Через numpy: 0.8717541573048718
Через scipy:
Корреляция: 0.8717541573048712
P_value: 1.0384540627942323e-47


In [12]:
# Проверка всего многомерного массива на наличие np.nan значений
# np.isnan ставит True/False в каждом массиве
# Далее any() для проверки есть хотя бы одна строка, где все True

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

res=np.isnan(iris_2d).any()
print(res)

False


In [15]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Локальный генератор
rng = np.random.default_rng(seed=100)

# ✅ ГЕНЕРИРУЕМ случайные индексы
n_rows = iris_2d.shape[0]  # 150 (размер)
n_cols = 4                  # 4 (размер)

# Генерируем 20 случайных номеров строк (от 0 до 149)
rows = rng.integers(0, n_rows, size=20)

# Генерируем 20 случайных номеров столбцов (от 0 до 3)
cols = rng.integers(0, n_cols, size=20)

# Заменяем на NaN
iris_2d[rows, cols] = np.nan

print(iris_2d[:10])



print(f'С np.nan: {iris_2d[:10]}')

# Заменяем на нули
iris_2d[np.isnan(iris_2d)] = 0
print(f'С нулями: {iris_2d[:10]}')


[[nan 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 nan 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
С np.nan: [[nan 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 nan 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
С нулями: [[0.  3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 0.  0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [23]:
# Распределние, количество уникальных элементов массиве

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species=iris[0:,4]

# Или явно преобразовать
# species = np.array([row.tolist()[4] for row in iris])

res=np.unique(species, return_counts=True)
res

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object),
 array([50, 50, 50]))

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')

petallength=iris[0:,3]

conditions=[petallength<3, (petallength>3) & (petallength<5), petallength>5]
choices=['small', 'medium', 'large']

petallength=np.select(conditions, choices, 'large')
petallength

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'sma

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris_2d[:5])

sepallength=iris_2d[0:,0].astype('float')
petallength=iris_2d[0:,2].astype('float')

# NumPy выполняет векторизованные операции — применяет формулу к каждому элементу
v=(np.pi * sepallength * (petallength**2))/3
print(v.shape)

# Ввести новое измерение, соответствующее iris_2d, чтобы можно было использовать векторизацию
v = v[:, np.newaxis]
print(v.shape)


# Добавить новый столбец
iris_2d = np.hstack([iris_2d, v])
print(iris_2d[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
(150,)
(150, 1)
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 10.467786721761188]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 10.057285281692124]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 8.317890149154577]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 10.838494654884785]
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa' 10.262536001726657]]


In [17]:
# Нужно сделать взвешенную случайную выборку, где setosa выпадает в 2 раза чаще, чем каждый из других видов.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Если versicolor и virginica имеют вероятность p, а setosa — 2p:
# 2p + p + p = 1
# 4p = 1
# p = 0.25

# Итоговые вероятности:
# setosa: 0.5 (50%)
# versicolor: 0.25 (25%)
# virginica: 0.25 (25%)

# Шаг 1: Извлекаем столбец species (последний, индекс 4)
species = iris[:, 4]

# Шаг 2: Находим уникальные значения
unique_species = np.unique(species)
print("Уникальные виды:", unique_species)

# Шаг 3: Задаём вероятности
# setosa в 2 раза чаще → [0.5, 0.25, 0.25]
probabilities = [0.5, 0.25, 0.25]

# Шаг 4: Делаем 150 случайных выборок с этими вероятностями
rng = np.random.default_rng(seed=100)
sampled = rng.choice(unique_species, size=150, p=probabilities)

# Шаг 5: Считаем, сколько раз выпал каждый вид
res = np.unique(sampled, return_counts=True)
res

Уникальные виды: [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object),
 array([63, 47, 40]))

In [25]:
# Фильтрация "строк" многомерного массива по значениям в "столбце"

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Шаг 1: Создаем булеву маску для вида 'setosa'
# ВАЖНО: из-за dtype='object' строки загружаются как байтовые (с префиксом b)
mask = iris[:, 4] == b'Iris-setosa'

# Шаг 2: Извлекаем petallength (столбец 2) только для setosa и преобразуем в float
setosa_petals = iris[mask, 2].astype(float)

# Шаг 3: Находим второе по величине значение
# Сортируем массив по возрастанию и берем предпоследний элемент [-2]
# Чтобы не учитывать дубликаты оборачиваем в np.unique
second_largest = np.sort(np.unique(setosa_petals))[-2]

print("Отсортированные длины лепестков setosa:")
print(np.sort(setosa_petals))
print(f"\nВторая по величине длина лепестка у setosa: {second_largest}")


Отсортированные длины лепестков setosa:
[1.  1.1 1.2 1.2 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.4 1.4 1.4 1.4 1.4 1.4 1.4
 1.4 1.4 1.4 1.4 1.4 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5
 1.5 1.6 1.6 1.6 1.6 1.6 1.6 1.6 1.7 1.7 1.7 1.7 1.9 1.9]

Вторая по величине длина лепестка у setosa: 1.7


In [31]:
# Сортировка многомерного массива по столбцу
# Сначала преобразуем в число, потом получаем индексы

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# 1. Берем нужный столбец (индекс 0) и преобразуем в float для корректной числовой сортировки
# (Без astype(float) строки '10.0' могут встать раньше '2.0' при лексикографической сортировке)
column_to_sort = iris[:, 0].astype(float)

# 2. Получаем ИНДЕКСЫ, которые отсортируют этот столбец
sort_indices = np.argsort(column_to_sort)

# 3. Применяем эти индексы ко всему 2D массиву
print(f'До сортировки: {iris[:5]}')
iris_sorted = iris[sort_indices]
print(f'После сортировки: {iris_sorted[:5]}')

До сортировки: [[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
После сортировки: [[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']]


In [17]:
# Группировка в NumPy если нельзя использовать pandas

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris[:5])

species=iris[0:,4]
sepalwidth=iris[0:,1].astype(float)

# Находим уникальные виды
unique_species = np.unique(species)

# Для каждого вида считаем среднее
result = []
for sp in unique_species:
    mask = (species == sp)              # булева маска для этого вида
    avg = sepalwidth[mask].mean()   # среднее по маске
    result.append([sp, avg])

result = np.array(result, dtype=object)
print(result)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
[[b'Iris-setosa' np.float64(3.418)]
 [b'Iris-versicolor' np.float64(2.7700000000000005)]
 [b'Iris-virginica' np.float64(2.974)]]


In [34]:
# Идиоматичное нахождение моды в массиве

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petallength=iris[0:,2]

# Идиоматичный поиск моды
values, counts = np.unique(petallength, return_counts=True)
print(np.unique(petallength, return_counts=True))

mode_value = values[np.argmax(counts)]
mode_count = counts[np.argmax(counts)]

print(f"Мода (наиболее частое значение): {mode_value}")
print(f"Количество повторений: {mode_count}")

(array([b'1.0', b'1.1', b'1.2', b'1.3', b'1.4', b'1.5', b'1.6', b'1.7',
       b'1.9', b'3.0', b'3.3', b'3.5', b'3.6', b'3.7', b'3.8', b'3.9',
       b'4.0', b'4.1', b'4.2', b'4.3', b'4.4', b'4.5', b'4.6', b'4.7',
       b'4.8', b'4.9', b'5.0', b'5.1', b'5.2', b'5.3', b'5.4', b'5.5',
       b'5.6', b'5.7', b'5.8', b'5.9', b'6.0', b'6.1', b'6.3', b'6.4',
       b'6.6', b'6.7', b'6.9'], dtype=object), array([ 1,  1,  2,  7, 12, 14,  7,  4,  2,  1,  2,  2,  1,  1,  1,  3,  5,
        3,  4,  2,  4,  8,  3,  5,  4,  5,  4,  8,  2,  2,  2,  3,  6,  3,
        3,  2,  2,  3,  1,  1,  1,  2,  1]))
Мода (наиболее частое значение): b'1.5'
Количество повторений: 14


In [7]:
# Поиск позиции первого элемента в массиве, удовлетворяющее определенному условию

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

indices=np.argwhere(iris[:, 3].astype(float) > 1.0)[0]
indices

array([50])

In [14]:
np.random.default_rng(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Использовать np.clip, но подходит только для максимума и минимума
# np.clip(a, a_min=10, a_max=30)

conditions=[a>30, a<10]
choices=[30, 10]

a=np.select(conditions, choices, default=a)
a

[25.51743894 36.08747854 26.77184088  1.06855213 20.34031405 25.11618153
 20.74113624 18.36061671 25.53010165 22.81365481  5.43120662 14.40458308
 47.23037779  2.30068743  2.95993579 14.87387763 29.53486434 49.55374734
 49.63946963 49.66275125]


array([25.51743894, 30.        , 26.77184088, 10.        , 20.34031405,
       25.11618153, 20.74113624, 18.36061671, 25.53010165, 22.81365481,
       10.        , 14.40458308, 30.        , 10.        , 10.        ,
       14.87387763, 29.53486434, 30.        , 30.        , 30.        ])

In [34]:
# Получение позиций 5 максимальных элементов в массиве

# Для больших массивов использовать np.argpartition

rng = np.random.default_rng(100)
a = rng.uniform(1, 50, 20)
print(a)

# Получаем индексы, сортирующие массив, и берем последние 5
# [::-1] переворачивает их, чтобы самый большой был первым (опционально)
top_5_indices = np.argsort(a)[-5:]
print(top_5_indices)




[41.91409989 30.23114732 15.15429884  3.10462696 48.70906536 30.2271135
 39.72289506 45.60662968 34.71956793 10.3095822  49.09247005 14.95226245
 31.83438532 29.47078746 30.39570138 27.22715716 49.79307811 25.59535815
 38.78010624 25.21392715]
[ 0  7  4 10 16]


In [ ]:
rng=np.random.default_rng(100)
arr = rng.integers(1, 11, size=(6, 10))
print(arr)

# 1. Создаем массив целевых значений [1, 2, 3, ..., 10]
targets = np.arange(1, 11)

# 2. Сравниваем arr с targets. 
# arr[:, :, None] добавляет третье измерение, чтобы сработало вещание (broadcasting)
# Результат сравнения: массив True/False размером (6, 10, 10)
matches = (arr[:, :, None] == targets)


#                     matches[0] (10×10)
#                    
#         1  2  3  4  5  6  7  8  9 10   ← targets
#       ┌──────────────────────────────┐
#  (8)  │  ·  ·  ·  ·  ·  ·  ·  ●  ·  · │  ← pos 0
#  (9)  │  ·  ·  ·  ·  ·  ·  ·  ·  ●  · │  ← pos 1
#  (2)  │  ·  ●  ·  ·  ·  ·  ·  ·  ·  · │  ← pos 2
#  (6)  │  ·  ·  ·  ·  ·  ●  ·  ·  ·  · │  ← pos 3
#  (1)  │  ●  ·  ·  ·  ·  ·  ·  ·  ·  · │  ← pos 4
#  (3)  │  ·  ·  ●  ·  ·  ·  ·  ·  ·  · │  ← pos 5
#  (5)  │  ·  ·  ·  ·  ●  ·  ·  ·  ·  · │  ← pos 6
#  (1)  │  ●  ·  ·  ·  ·  ·  ·  ·  ·  · │  ← pos 7
#  (6)  │  ·  ·  ·  ·  ·  ●  ·  ·  ·  · │  ← pos 8
# (10)  │  ·  ·  ·  ·  ·  ·  ·  ·  ·  ● │  ← pos 9
#       └──────────────────────────────┘
#            ↓  ↓  ↓  ↓  ↓  ↓  ↓  ↓  ↓  ↓
#  sum:     2  1  1  0  1  2  0  1  1  1    ← результат
#           ↑                              ↑
#    "сколько раз число k встречается в строке"


# 3. Суммируем по оси 1 (грубо говоря по столбцам)
# True превращается в 1, False в 0. Сумма даст количество совпадений.
result = matches.sum(axis=1)
print(result)



[[ 8  9  2  6  1  3  5  1  6 10]
 [10  6  5  8 10 10  1  7  8  2]
 [ 6 10  7  3  4  7  2  6  6  6]
 [ 8  6  8 10  2  6  2  8  2  5]
 [ 3 10  5 10  9  4  5  4  9  9]
 [ 5  8 10  7  8  5 10  4  7  2]]
[[2 1 1 0 1 2 0 1 1 1]
 [1 1 0 0 1 1 1 2 0 3]
 [0 1 1 1 0 4 2 0 0 1]
 [0 3 0 0 1 2 0 3 0 1]
 [0 0 1 2 2 0 0 0 3 2]
 [0 1 0 1 2 0 2 2 0 2]]


In [50]:
# Создание плоского (1-D) массива из нескольких

arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

array_of_arrays = np.array([arr1, arr2, arr3], dtype=object)
print(array_of_arrays)

res=np.hstack((arr1,arr2, arr3))
res2=np.concatenate((arr1,arr2, arr3), axis=None)

res,res2

[array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [6]:
# One-hot — это способ преобразовать категориальные значения в бинарные векторы
# Используем broadcasting для создания True/False массива

rng=np.random.default_rng(101)
arr = rng.integers(1, 4, size=6)
print(arr)

# Шаг 1: Находим уникальные значения (отсортированы!)
unique_values = np.unique(arr)
print("Уникальные значения:", unique_values)

# Шаг 2: Сравниваем каждый элемент arr с каждым уникальным значением
# arr[:, None] превращает (6,) → (6, 1) для broadcasting
# unique_values имеет форму (3,)
# Результат сравнения: (6, 3) — матрица True/False
one_hot_bool = (arr[:, None] == unique_values)
print(one_hot_bool)

# Шаг 3: Преобразуем True/False в 1/0
one_hot = one_hot_bool.astype(int)

print("\nOne-hot кодировка:")
print(one_hot)


[1 3 3 2 1 3]
Уникальные значения: [1 2 3]
[[ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]]

One-hot кодировка:
[[1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]]


In [9]:
#  Группированная нумерация строк полезна для создания последовательных 
# признаков и ранжирования внутри категорий в анализе данных.


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

rng=np.random.default_rng(100)
species_small = np.sort(rng.choice(species, size=20))
print(species_small)

# 1. Находим уникальные виды и СКОЛЬКО РАЗ каждый из них встречается
# (return_counts=True вернет массив количеств, например: [14, 4, 2])
unique_species, counts = np.unique(species_small, return_counts=True)

print(f'unique_species: {unique_species}')
print(f'counts: {counts}')

# 2. Для каждого количества генерируем массив [0, 1, 2, ... count-1]
# и склеиваем их все в один плоский массив
result = np.concatenate([np.arange(count) for count in counts])
result

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']
unique_species: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
counts: [6 5 9]


array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
# Параметр return_inverse=True заставляет np.unique вернуть второй массив (group_ids), 
# который содержит индексы, необходимые для восстановления исходного массива из уникальных значений.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

rng=np.random.default_rng(100)
species_small = np.sort(rng.choice(species, size=20))
print(species_small)

# === ИДИОМАТИЧНОЕ РЕШЕНИЕ ===
unique_categories, group_ids = np.unique(species_small, return_inverse=True)
group_ids

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
# Ранжирование в numpy

# np.argsort(a).
# Эта функция отвечает на вопрос: "В каком порядке мне нужно брать индексы исходного массива, чтобы получить отсортированный массив?"

# В NumPy ранг вычисляется с помощью двойного argsort
# Первый np.argsort(a) говорит: "Элемент с индексом 7 самый маленький (ранг 0)".
# Второй np.argsort переворачивает эту логику и говорит: "Элемент, который изначально стоял на месте 0, имеет ранг 6".



rng=np.random.default_rng(10)
a = rng.integers(20, size=10)
print(a)

print(np.sort(a))

indices=np.argsort(a)
print(indices)

a.argsort().argsort()


[15 19  5  4 15 16 10  2 16 10]
[ 2  4  5 10 10 15 15 16 16 19]
[7 3 2 6 9 4 0 5 8 1]


array([6, 9, 2, 1, 5, 7, 3, 0, 8, 4])

In [59]:
# Ранжирование многомерного массива с сохранением структуры в новом массиве рангов
# Вначале нужно сделать массив плоским

rng=np.random.default_rng(10)
a = rng.integers(20, size=[2, 5])
print(a)


# reshape(a.shape) позволяет не подгонять размерность массива вручную, а сама подстроится под исходный
res = np.argsort(np.argsort(a.ravel())).reshape(a.shape)
res


[[15 19  5  4 15]
 [16 10  2 16 10]]


array([[6, 9, 2, 1, 5],
       [7, 3, 0, 8, 4]])

In [66]:
# Вычислите максимальное значение для каждой строки в двумерном массиве a

rng=np.random.default_rng(100)
а = rng.integers(1, 10, [5, 3])
print(a)

res=a.max(axis=1)
res

[[15 19  5  4 15]
 [16 10  2 16 10]]


array([19, 16])

In [74]:
rng=np.random.default_rng(100)
а = rng.integers(1, 10, [5, 3])
print(a)

res=a.min(axis=1)/a.max(axis=1)
res



[[15 19  5  4 15]
 [16 10  2 16 10]]


array([0.21052632, 0.125     ])

In [14]:
# Поиск повторяющихся записей в массиве
# Пометка повторных вхождений как True

rng=np.random.default_rng(100)
a = rng.integers(0, 5, 10)
print('Массив: ', a)

u, indices=np.unique(a, return_index=True)
print(u)
print(indices)

# Создаём массив True (все считаем дубликатами)
is_duplicate = np.ones(len(a), dtype=bool)
print(is_duplicate)

is_duplicate[indices]=False

is_duplicate

Массив:  [3 4 0 2 0 1 2 0 2 4]
[0 1 2 3 4]
[2 5 3 0 1]
[ True  True  True  True  True  True  True  True  True  True]


array([False, False, False, False,  True, False,  True,  True,  True,
        True])

In [22]:
# Скачивание изображения и преобразование в numpy массив

# 303 — высота изображения в пикселях (количество строк).
# 452 — ширина изображения в пикселях (количество столбцов).
# 3 — количество цветовых каналов (Red, Green, Blue).


import numpy as np
from io import BytesIO
from PIL import Image
import PIL, requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'


# 1. Добавляем заголовок, чтобы сервер не блокировал запрос
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
}

# Скачиваем с заголовками
response = requests.get(URL, headers=headers)

# 2. Открываем изображение из потока байтов в памяти с помощью PIL
img = Image.open(BytesIO(response.content))

# 3. Преобразуем объект изображения PIL в массив NumPy
img_array = np.array(img)

# 4. Выводим форму массива
print("Форма массива (Shape):", img_array.shape)
print("Тип данных:", img_array.dtype)

Форма массива (Shape): (303, 452, 3)
Тип данных: uint8
