In [1]:
import numpy as np
import pandas as pd

In [3]:
lst=np.arange(0,10,1)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Создание массива любой размерности, любым значением и типом данных

arr3=np.full((3,3), True, dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Фильтрация np.array через маску

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
# Замена значений через маску или np.where

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.where(arr%2!=0,-1,arr)

# Или
# arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
arr = np.arange(10)
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# вертикальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=0)

# Или
# np.vstack((a, b))

# Или 
# np.r_[a, b]
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# горизонтальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=1)
res

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# Генерация повторяющейся последовательности элементов по разным паттернам

a = np.array([1,2,3])

res=np.repeat(a, 3)
print(res)

res2=np.tile(a,3)
print(res2)

result=np.r_[np.repeat(a, 3), np.tile(a,3)]
result

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [3]:
# Поиск общих уникальных элементов в двух массивах

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.intersect1d(a,b)
res

array([2, 4])

In [10]:
# Фильтрация массива по наличию общих элементов с другим массивом

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])


res=np.setdiff1d(a,b)
res

array([1, 2, 3, 4])

In [27]:
# Поиск позиций, где элементы совпадают

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

res=np.where(a==b)
res

(array([1, 3, 5, 7]),)

In [32]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

# Метод 2:
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])

# Метод 3:
# index = np.where(np.logical_and(a>=5, a<=10))
# print(a[index])

array([ 6,  9, 10])

In [40]:
# Пример квази-векторизации через np.vecrotize


# Лучше использовать встроенную векторизованную функцию, она в сотни раз быстрее
# res = np.maximum(a, b)

def maxx(x, y):
    "Получите максимум два предмета"
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

res = np.vectorize(maxx, otypes=[float])(a,b)

res

array([6., 7., 9., 8., 9., 7., 5.])

In [5]:
# Изменение порядка элементов во вложенных массивах (столбцах)

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[:, [1,0,2]]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [9]:
# Изменение порядка элементов во вложенных массивах (строках)

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[[1,0,2], :]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [15]:
# Сортировка в обратном порядке строк

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[::-1]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [33]:
lst=[0,1,2]
lst[::-1]

[2, 1, 0]

In [37]:
# Обратная сортировка столбцов в многомерном массиве

arr = np.arange(9).reshape(3,3)
print(arr)

res=arr[:,::-1]
res

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [63]:
# Генерация массива float от 5 до 10 с заданным shape через новый API np.random

rng = np.random.default_rng(seed=42)
arr = rng.uniform(5, 10, (5, 3))
arr

array([[8.86978024, 7.1943922 , 9.2929896 ],
       [8.48684015, 5.47088674, 9.87811176],
       [8.80569851, 8.93032153, 5.64056816],
       [7.25192969, 6.85399012, 9.63382494],
       [8.2193256 , 9.11380807, 7.21707099]])

In [66]:
# Ограничение до 3 знаков после запятой
# Аналог pd.get/set_options в pandas

rand_arr = np.random.random((5,3))


np.set_printoptions(precision=3)

rand_arr

array([[0.924, 0.526, 0.92 ],
       [0.956, 0.025, 0.71 ],
       [0.242, 0.694, 0.21 ],
       [0.253, 0.242, 0.894],
       [0.017, 0.847, 0.84 ]])

In [68]:
np.set_printoptions(precision=6, suppress=True)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [69]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [71]:
import sys

np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [72]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Вывести первые 3 строки
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]
