In [1]:
import numpy as np
import pandas as pd

In [3]:
lst=np.arange(0,10,1)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Создание массива любой размерности, любым значением и типом данных

arr3=np.full((3,3), True, dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Фильтрация np.array через маску

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
# Замена значений через маску или np.where

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.where(arr%2!=0,-1,arr)

# Или
# arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
arr = np.arange(10)
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# вертикальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=0)

# Или
# np.vstack((a, b))

# Или 
# np.r_[a, b]
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# горизонтальное объединение двух np.array

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

res=np.concatenate((a,b), axis=1)
res

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# Генерация повторяющейся последовательности элементов по разным паттернам

a = np.array([1,2,3])

res=np.repeat(a, 3)
print(res)

res2=np.tile(a,3)
print(res2)

result=np.r_[np.repeat(a, 3), np.tile(a,3)]
result

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])