In [1]:
import numpy as np
import pandas as pd

In [3]:
lst=np.arange(0,10,1)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Создание массива любой размерности, любым значением и типом данных

arr3=np.full((3,3), True, dtype=bool)
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Фильтрация np.array через маску

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [8]:
# Замена значений через маску или np.where

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.where(arr%2!=0,-1,arr)

# Или
# arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])